config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, alert: 'article created successfully.'
    else
      redirect_to new_article_path, alert: 'Error creating article.'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path, alert: 'article updated successfully.'
    else
      redirect_to new_article_path, alert: 'Error updating article.'
    end
  end

  def destroy
    @article.delete
    redirect_to articles_path, alert: 'article updated successfully.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>
<ol>
  <% @articles.each do |article| %>
  <li>
    <p><%= article.title %></p>
    <%= link_to 'More details', article_path(article) %>
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Delete', article_path(article), method: :delete %>
  </li>
  <% end %>
</ol>
<br />
<br />
<br />
<%= link_to 'Create new article', new_article_path %>

app/views/articles/new.html.erb
<h1>articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.select :completed, [true, false]%>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1>articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

<p>Title: <%= @article.title %></p>
<p>Details: <%= @article.content %></p>

<%= link_to 'back to home', articles_path %>
<%= link_to 'edit', edit_article_path %>
<%= link_to 'delete', article_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>